language: ruby
cache: bundler
before_install:
- gem install bundler
- bundle install
after_success:
- script/tag_on_master
script: bundle exec rake book:build
deploy:
  provider: releases
  api_key:
    secure: XT3fnofLU13ZpmZX4jXVbG2mLIMvjkFKS4TGLjNwJKdhLyZQqmP6kVzsZl8RGknkfPe8IOudXfnaQn/v8eJYrJXIiVXJlZyn///E7tLr0dYwj3wCPaIv0F04rJAhwqA6pPLDvY53b5EG0vqPbg28P0qFLPbk3KIIUFJmot3gzU0=
  file:
  - progit.epub
  - progit.mobi
  - progit.pdf
  skip_cleanup: true
  on:
    tags: true
branches:
  only:
  - master
  - /^2\.1(\.\d+)+$/
